INSERT INTO `ingredient` VALUES ('CARN', 'Carnitas', '1');
INSERT INTO `ingredient` VALUES ('CHED', 'Cheddar', '3');
INSERT INTO `ingredient` VALUES ('COTO', 'Corn Tortilla', '0');
INSERT INTO `ingredient` VALUES ('FLTO', 'Flour Tortilla', '0');
INSERT INTO `ingredient` VALUES ('GRBF', 'Ground Beef', '1');
INSERT INTO `ingredient` VALUES ('JACK', 'Monterrey Jack', '3');
INSERT INTO `ingredient` VALUES ('LETC', 'Lettuce', '2');
INSERT INTO `ingredient` VALUES ('SLSA', 'Salsa', '4');
INSERT INTO `ingredient` VALUES ('SRCR', 'Sour Cream', '4');
INSERT INTO `ingredient` VALUES ('TMTO', 'Diced Tomatoes', '2');